[package]
name = "revenue-sharing-solana"
version = "0.1.0"
edition = "2018"
license = "WTFPL"
publish = false

[dependencies]
solana-program = "1.6.9"
spl-token = {version = "3.1.1", features = ["no-entrypoint"]}
thiserror = "1.0.24"
arrayref = "0.3.6"

[lib]
crate-type = ["cdylib", "lib"]
